name: Deploy
on: push
jobs:
  container-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci --loglevel verbose
      - name: Spago install
        run: npx spago -x test.dhall install
      - name: Spago build
        run: npx spago -x test.dhall build
      - name: Test
        run: npm test
      - name: Build qc
        run: npm run build:storybook
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./dist