name: Sanity chcek
on: push
jobs:
  container-job:
    runs-on: ubuntu-latest
    container: node:10.18-jessie
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Spago install
        run: npx spago -x starters.dhall install
      - name: Spago build
        run: npx spago -x starters.dhall build
